DATA_SPLITS:
  train_test_ratio: 0.9
  train_valid_ratio: 0.85

RANDOM_SEED: null

DATASET: CustomImageFolder

DATA_LOADER:
  batch_size: 16
  num_workers: 2
  pin_memory: True

DATA_TRANSFORM_AND_AUGMENTATION:
  train:
    Resize: 
        size: [224, 224]
    RandAugment: 
        num_ops: 3
        magnitude: 10
    TrivialAugmentWide:
        num_magnitude_bins: 31
    ToTensor: {}
    Normalize: {}
  test:
    Resize: 
        size: [224, 224]
    ToTensor: {}
    Normalize: {}

MODEL_PARAMS:
  hidden_units: 32
  epochs: 500
  loss_func: CrossEntropyLoss
  metrics : [accuracy, precision, recall, f1]
  torchmetrics:
    ConfusionMatrix:
      task: multiclass
      num_classes: 4
  activation_func: ReLU
  optimizer: 
    Adam:
      lr: 0.0001
  lr_scheduler:
    ReduceLROnPlateau:
      mode: min
      factor: 0.25
      patience: 5
  early_stopping:
    patience: 8
    delta: 0
    saving_option: model
    verbose: True






