DATA_SPLITS:
  TRAIN_TEST_RATIO: 0.9
  TRAIN_VALID_RATIO: 0.85

RANDOM_SEED: null

DATASET: CustomImageFolder

DATA_LOADER:
  BATCH_SIZE: 16

DATA_TRANSFORM_AND_AUGMENTATION:
  train:
    Resize: 
        size: [224, 224]
    RandAugment: 
        num_ops: 2
        magnitude: 10
    TrivialAugmentWide:
        num_magnitude_bins: 31
    ToTensor: {}
    Normalize: {}
  test:
    Resize: 
        size: [224, 224]
    ToTensor: {}
    Normalize: {}
MODEL_PARAMS:
  HIDDEN_UNITS: 10
  EPOCHS: 10
  OPTIMIZER: 
    Adam:
      lr: 0.001
  LOSS_FUNC: CrossEntropyLoss