RANDOM_SEED: null

DATA_LOADER:
  BATCH_SIZE: 16

DATA_TRANSFORM_AND_AUGMENTATION:
  Resize: 
      size: [224, 224]
  RandAugment: 
      num_ops: 2
      magnitude: 10
  TrivialAugmentWide:
      num_magnitude_bins: 31
  ToTensor: {}

MODEL_PARAMS:
  HIDDEN_UNITS: 10
  EPOCHS: 10
  OPTIMIZER: 
    Adam:
      lr: 0.001
  LOSS_FUNC: CrossEntropyLoss